"""user table

Revision ID: 7a23be3fa599
Revises:
Create Date: 2026-06-28 21:37:49.731887

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a23be3fa599"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plan", sa.Enum("free", "pro", "enterprise", name="plan"), nullable=False),
        sa.Column("monthly_minutes_used", sa.Float(), nullable=False),
        sa.Column("twilio_phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # create_table auto-creates the `plan` enum type but the autogenerated
    # downgrade does not drop it; drop it explicitly so the migration is
    # symmetric and re-appliable.
    sa.Enum(name="plan").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
