# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audio_pb2 as audio__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceConversionStub:
    """VoiceConversion is the gateway <-> inference contract. The gateway terminates
    the browser WebSocket and proxies each session's audio frames here over a
    single bidirectional stream; the inference service transforms each frame and
    streams it back. Frame format mirrors the browser/WS contract in
    agents/AGENTS.md: Int16 PCM, 20ms / 960 samples at 48kHz.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.stream_stream(
                '/mockingbird.audio.v1.VoiceConversion/Convert',
                request_serializer=audio__pb2.AudioFrame.SerializeToString,
                response_deserializer=audio__pb2.AudioFrame.FromString,
                _registered_method=True)


class VoiceConversionServicer:
    """VoiceConversion is the gateway <-> inference contract. The gateway terminates
    the browser WebSocket and proxies each session's audio frames here over a
    single bidirectional stream; the inference service transforms each frame and
    streams it back. Frame format mirrors the browser/WS contract in
    agents/AGENTS.md: Int16 PCM, 20ms / 960 samples at 48kHz.
    """

    def Convert(self, request_iterator, context):
        """One bidirectional stream per active WebSocket session. Frames are 1:1 —
        each AudioFrame in yields one transformed AudioFrame out, in order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceConversionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Convert': grpc.stream_stream_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=audio__pb2.AudioFrame.FromString,
                    response_serializer=audio__pb2.AudioFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mockingbird.audio.v1.VoiceConversion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mockingbird.audio.v1.VoiceConversion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceConversion:
    """VoiceConversion is the gateway <-> inference contract. The gateway terminates
    the browser WebSocket and proxies each session's audio frames here over a
    single bidirectional stream; the inference service transforms each frame and
    streams it back. Frame format mirrors the browser/WS contract in
    agents/AGENTS.md: Int16 PCM, 20ms / 960 samples at 48kHz.
    """

    @staticmethod
    def Convert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mockingbird.audio.v1.VoiceConversion/Convert',
            audio__pb2.AudioFrame.SerializeToString,
            audio__pb2.AudioFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
